# Generated by Django 5.2.17 on 2026-08-26 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('name', models.CharField(max_length=180, verbose_name='Name')),
                ('organization', models.CharField(blank=True, max_length=180, verbose_name='Organisation/Verein')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=80, verbose_name='Telefon')),
                ('street', models.CharField(blank=True, max_length=180, verbose_name='Straße/Hausnummer')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ort')),
                ('notes', models.TextField(blank=True, verbose_name='Interne Notizen')),
            ],
            options={
                'verbose_name': 'Entleiher',
                'verbose_name_plural': 'Entleiher',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('inventory_number', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Inventarnummer')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('stock_quantity', models.PositiveIntegerField(default=1, verbose_name='Bestand')),
                ('storage_location', models.CharField(blank=True, max_length=160, verbose_name='Lagerort')),
                ('condition_note', models.TextField(blank=True, verbose_name='Zustand/Bemerkung')),
                ('suggested_donation', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Spendenempfehlung')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Kaution')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='rental.productcategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Verleihartikel',
                'verbose_name_plural': 'Verleihartikel',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RentalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Vorgangsnummer')),
                ('reserved_from', models.DateTimeField(verbose_name='Reserviert von')),
                ('reserved_until', models.DateTimeField(verbose_name='Reserviert bis')),
                ('status', models.CharField(choices=[('request', 'Anfrage'), ('reserved', 'Reserviert'), ('prepared', 'Abholung vorbereitet'), ('handed_over', 'Übergeben'), ('donation_open', 'Spende offen'), ('donation_received', 'Spende erhalten'), ('returned', 'Zurückgenommen'), ('clarification', 'Klärung nötig'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='request', max_length=32, verbose_name='Status')),
                ('expected_donation', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Erwartete Spende')),
                ('received_donation', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Erhaltene Spende')),
                ('donation_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Spende erhalten am')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_cases', to='rental.borrower', verbose_name='Entleiher')),
            ],
            options={
                'verbose_name': 'Verleihvorgang',
                'verbose_name_plural': 'Verleihvorgänge',
                'ordering': ['-reserved_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('protocol_type', models.CharField(choices=[('handover', 'Übergabeprotokoll'), ('return', 'Rücknahmeprotokoll')], max_length=20, verbose_name='Protokolltyp')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Durchgeführt am')),
                ('borrower_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Unterschrift Entleiher')),
                ('club_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Unterschrift Verein')),
                ('notes', models.TextField(blank=True, verbose_name='Protokollnotizen')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='PDF')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_protocols', to=settings.AUTH_USER_MODEL, verbose_name='Helfer')),
                ('rental_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='rental.rentalcase', verbose_name='Vorgang')),
            ],
            options={
                'verbose_name': 'Protokoll',
                'verbose_name_plural': 'Protokolle',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('document_type', models.CharField(choices=[('reservation', 'Reservierungsbestätigung'), ('handover', 'Übergabeprotokoll'), ('return', 'Rücknahmeprotokoll'), ('closing', 'Abschlussübersicht')], max_length=32, verbose_name='Dokumenttyp')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Datei')),
                ('sent_to', models.EmailField(blank=True, max_length=254, verbose_name='Gesendet an')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('send_error', models.TextField(blank=True, verbose_name='Versandfehler')),
                ('rental_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rental.rentalcase', verbose_name='Vorgang')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalCaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('handover_condition', models.TextField(blank=True, verbose_name='Zustand bei Übergabe')),
                ('return_condition', models.TextField(blank=True, verbose_name='Zustand bei Rücknahme')),
                ('missing', models.BooleanField(default=False, verbose_name='Fehlt')),
                ('damaged', models.BooleanField(default=False, verbose_name='Beschädigt')),
                ('damage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Schadenbetrag')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_items', to='rental.product', verbose_name='Artikel')),
                ('rental_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.rentalcase', verbose_name='Vorgang')),
            ],
            options={
                'verbose_name': 'Vorgangsposition',
                'verbose_name_plural': 'Vorgangspositionen',
                'unique_together': {('rental_case', 'product')},
            },
        ),
    ]
