# Generated by Django 5.2.17 on 2026-08-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='replacement_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ersatzwert'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Verfügbar'), ('maintenance', 'Wartung'), ('defective', 'Defekt'), ('retired', 'Ausgemustert')], default='available', max_length=24, verbose_name='Artikelstatus'),
        ),
        migrations.CreateModel(
            name='ProductAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('name', models.CharField(max_length=160, verbose_name='Zubehör/Bestandteil')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('required', models.BooleanField(default=True, verbose_name='Pflichtbestandteil')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='rental.product', verbose_name='Artikel')),
            ],
            options={
                'verbose_name': 'Zubehör/Bestandteil',
                'verbose_name_plural': 'Zubehör/Bestandteile',
                'ordering': ['product__name', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
