# Generated by Django 5.2.17 on 2026-08-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_product_replacement_value_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcase',
            name='donation_decision',
            field=models.CharField(choices=[('open', 'Offen'), ('received', 'Erhalten'), ('partial', 'Teilweise erhalten'), ('waived', 'Verzichtet')], default='open', max_length=16, verbose_name='Spendenentscheidung'),
        ),
        migrations.AddField(
            model_name='rentalcase',
            name='donation_note',
            field=models.TextField(blank=True, verbose_name='Zahlungsnotiz'),
        ),
        migrations.AddField(
            model_name='rentalcase',
            name='donation_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Bar'), ('bank_transfer', 'Überweisung'), ('paypal', 'PayPal'), ('other', 'Sonstig')], max_length=24, verbose_name='Zahlungsart'),
        ),
    ]
