# Generated by Django 5.2.17 on 2026-08-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_donation_decision_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('image', models.ImageField(upload_to='protocol-photos/', verbose_name='Foto')),
                ('caption', models.CharField(blank=True, max_length=240, verbose_name='Beschreibung')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rental.protocol', verbose_name='Protokoll')),
            ],
            options={
                'verbose_name': 'Protokollfoto',
                'verbose_name_plural': 'Protokollfotos',
                'ordering': ['created_at'],
            },
        ),
    ]
