# Generated by Django 5.2.17 on 2026-08-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_protocolphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcaseitem',
            name='handover_accessories',
            field=models.ManyToManyField(blank=True, related_name='handover_items', to='rental.productaccessory', verbose_name='Mitgegebenes Zubehör'),
        ),
    ]
