# Generated by Django 5.2.17 on 2026-09-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_handover_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolphoto',
            name='rental_case_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_photos', to='rental.rentalcaseitem', verbose_name='Artikelposition'),
        ),
    ]
