# Generated by Django 5.2.17 on 2026-09-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_protocolphoto_rental_case_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='borrower_signature_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Name Entleiher-Unterschrift'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='club_signature_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Name Verein-/Helfer-Unterschrift'),
        ),
    ]
