# Generated by Django 5.2.17 on 2026-09-11 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_protocol_borrower_signature_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReceiptIssuerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('name', models.CharField(max_length=220, verbose_name='Vereinsname / Aussteller')),
                ('street', models.CharField(max_length=180, verbose_name='Straße/Hausnummer')),
                ('postal_code', models.CharField(max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(max_length=120, verbose_name='Ort')),
                ('tax_office', models.CharField(max_length=180, verbose_name='Finanzamt')),
                ('tax_number', models.CharField(max_length=80, verbose_name='Steuernummer')),
                ('exemption_notice_date', models.DateField(blank=True, null=True, verbose_name='Datum Freistellungs-/Körperschaftsteuerbescheid')),
                ('determination_notice_date', models.DateField(blank=True, null=True, verbose_name='Datum Feststellungsbescheid § 60a AO')),
                ('statutory_purposes', models.TextField(verbose_name='Begünstigte Zwecke')),
                ('default_issue_place', models.CharField(blank=True, max_length=120, verbose_name='Standard-Ausstellungsort')),
                ('default_signer_name', models.CharField(blank=True, max_length=180, verbose_name='Standard-Unterzeichner')),
                ('default_signer_function', models.CharField(blank=True, max_length=180, verbose_name='Funktion des Unterzeichners')),
                ('membership_fees_deductible', models.BooleanField(default=False, verbose_name='Mitgliedsbeiträge steuerlich abziehbar')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Vereinsdaten Zuwendungsbestätigung',
                'verbose_name_plural': 'Vereinsdaten Zuwendungsbestätigungen',
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('reservation', 'Reservierungsbestätigung'), ('handover', 'Übergabeprotokoll'), ('return', 'Rücknahmeprotokoll'), ('closing', 'Abschlussübersicht'), ('donation_receipt', 'Zuwendungsbestätigung')], max_length=32, verbose_name='Dokumenttyp'),
        ),
        migrations.CreateModel(
            name='DonationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('receipt_number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Bescheinigungsnummer')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('issued', 'Ausgestellt'), ('cancelled', 'Storniert')], default='draft', max_length=16, verbose_name='Status')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Ausgestellt am')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Storniert am')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Stornogrund')),
                ('donor_name', models.CharField(max_length=180, verbose_name='Name des Zuwendenden')),
                ('donor_organization', models.CharField(blank=True, max_length=180, verbose_name='Organisation')),
                ('donor_street', models.CharField(max_length=180, verbose_name='Straße/Hausnummer')),
                ('donor_postal_code', models.CharField(max_length=20, verbose_name='PLZ')),
                ('donor_city', models.CharField(max_length=120, verbose_name='Ort')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Betrag der Zuwendung')),
                ('donation_amount_words', models.CharField(blank=True, max_length=240, verbose_name='Betrag in Buchstaben')),
                ('donation_date', models.DateField(verbose_name='Tag der Zuwendung')),
                ('is_membership_fee', models.BooleanField(default=False, verbose_name='Mitgliedsbeitrag')),
                ('is_expense_reimbursement_waiver', models.BooleanField(default=False, verbose_name='Verzicht auf Erstattung von Aufwendungen')),
                ('issuer_name', models.CharField(max_length=220, verbose_name='Aussteller/Verein')),
                ('issuer_street', models.CharField(max_length=180, verbose_name='Straße/Hausnummer Verein')),
                ('issuer_postal_code', models.CharField(max_length=20, verbose_name='PLZ Verein')),
                ('issuer_city', models.CharField(max_length=120, verbose_name='Ort Verein')),
                ('tax_office', models.CharField(max_length=180, verbose_name='Finanzamt')),
                ('tax_number', models.CharField(max_length=80, verbose_name='Steuernummer')),
                ('exemption_notice_date', models.DateField(blank=True, null=True, verbose_name='Datum Freistellungs-/Körperschaftsteuerbescheid')),
                ('determination_notice_date', models.DateField(blank=True, null=True, verbose_name='Datum Feststellungsbescheid § 60a AO')),
                ('statutory_purposes', models.TextField(verbose_name='Begünstigte Zwecke')),
                ('membership_fees_deductible', models.BooleanField(default=False, verbose_name='Mitgliedsbeiträge steuerlich abziehbar')),
                ('issue_place', models.CharField(max_length=120, verbose_name='Ausstellungsort')),
                ('signer_name', models.CharField(max_length=180, verbose_name='Unterzeichner')),
                ('signer_function', models.CharField(max_length=180, verbose_name='Funktion')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_donation_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Storniert von')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_receipt', to='rental.document', verbose_name='Dokument')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_donation_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Ausgestellt von')),
                ('rental_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation_receipts', to='rental.rentalcase', verbose_name='Vorgang')),
            ],
            options={
                'verbose_name': 'Zuwendungsbestätigung',
                'verbose_name_plural': 'Zuwendungsbestätigungen',
                'ordering': ['-issued_at', '-created_at'],
                'permissions': [('can_issue_donation_receipt', 'Darf Zuwendungsbestätigungen ausstellen')],
            },
        ),
    ]
